news:
    resource: "@NewsBundle/Controller/"
    type:     annotation
    prefix:   /

# on supprime le bundle par défaut (AppBundle)
#app:
    #resource: '@AppBundle/Controller/'
    #type: annotation
